version: "3"

services:
  web:
    container_name: "nginx"
    build:
      dockerfile: "./docker/nginx/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - ./public:/app/public

  php:
    container_name: "php"
    build:
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - .:/app

  mysql:
    container_name: "mysql"
    build:
      dockerfile: "./docker/mysql/Dockerfile"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
